// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnNGjVeL3cx0TWRZEmksbQLU19FLVNKxU',
    appId: '1:194827125874:web:ce7da8b0cbe2dec0402eeb',
    messagingSenderId: '194827125874',
    projectId: 'first-login-app-410d4',
    authDomain: 'first-login-app-410d4.firebaseapp.com',
    storageBucket: 'first-login-app-410d4.firebasestorage.app',
    measurementId: 'G-T7ZWMP8N3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5lZSo_njpW1UFC5VykhVMDEUSNf9FRHo',
    appId: '1:194827125874:android:7707002fff055249402eeb',
    messagingSenderId: '194827125874',
    projectId: 'first-login-app-410d4',
    storageBucket: 'first-login-app-410d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1plNV_ETjP4PMssC3fX4aVJyh1eh8YTg',
    appId: '1:194827125874:ios:759e59fb49ad9651402eeb',
    messagingSenderId: '194827125874',
    projectId: 'first-login-app-410d4',
    storageBucket: 'first-login-app-410d4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1plNV_ETjP4PMssC3fX4aVJyh1eh8YTg',
    appId: '1:194827125874:ios:759e59fb49ad9651402eeb',
    messagingSenderId: '194827125874',
    projectId: 'first-login-app-410d4',
    storageBucket: 'first-login-app-410d4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnNGjVeL3cx0TWRZEmksbQLU19FLVNKxU',
    appId: '1:194827125874:web:1028efbac8269184402eeb',
    messagingSenderId: '194827125874',
    projectId: 'first-login-app-410d4',
    authDomain: 'first-login-app-410d4.firebaseapp.com',
    storageBucket: 'first-login-app-410d4.firebasestorage.app',
    measurementId: 'G-LGN09SJKPG',
  );
}
